propNames = {
  "1424": "Forbes",
  "1425": "Forbes",
  "1426": "Forbes",
  "1427": "Forbes",
  "1428": "Forbes",
  "1429": "Forbes",
  "1430": "Forbes",
  "1431": "Forbes",
  "1432": "Forbes",
  "LI-TJ9Q6KNJHQ": "Conde Nast Collections",
  "LI-HQEZIUAFSV": "Jezebel",
  "LI-54HHD3JCOI": "The Knot",
  "LI-VAGN1I8R6E": "USA TODAY Sports Media Group",
  "LI-GXYDVJX6PZ": "USA TODAY Sports Media Group",
  "LI-5Z8481TC4V": "Entrepreneur",
  "LI-XE9EUFGDNN": "Entrepreneur",
  "LI-X7FZIEX5EO": "Entrepreneur",
  "LI-T7JTDB17BO": "Entrepreneur",
  "LI-72WR70APPH": "Entrepreneur",
  "LI-T0KPWAJRG5": "Entrepreneur",
  "LI-KEFPW8VOFQ": "Entrepreneur",
  "LI-CRTUW7MWMR": "Entrepreneur",
  "LI-7WF6NYML5W": "Entrepreneur",
  "LI-3675F04VI6": "Entrepreneur",
  "LI-JM1WCH3A5A": "Entrepreneur",
  "LI-F8MI9V9ZYP": "Entrepreneur",
  "LI-TT2GIO65JK": "Entrepreneur",
  "LI-EZS49KB1JG": "Entrepreneur",
  "LI-XZ111YP4AF": "Entrepreneur",
  "LI-0P7HD7TG77": "Entrepreneur",
  "LI-C5W2M3UIY3": "Entrepreneur",
  "LI-Q5WMJQ21CE": "Entrepreneur",
  "LI-7MOMOADRTV": "Entrepreneur",
  "LI-7YDBI7MG5J": "Entrepreneur",
  "LI-SNFPYJY6S7": "Entrepreneur",
  "LI-NJV1DCMYCO": "Entrepreneur",
  "LI-53E81TIYOP": "Entrepreneur",
  "LI-1UIC2853LH": "Entrepreneur",
  "LI-KVLL11IHP3": "Forbes",
  "LI-OJYSIMI57K": "Forbes",
  "LI-K5NULWF62S": "Forbes",
  "LI-U92G93Y0H7": "Forbes",
  "LI-RVG417QVND": "The Fashionisto",
  "LI-D3HTIZO1P2": "The Fashionisto",
  "LI-O9BO7RERJO": "The Fashionisto",
  "LI-JVV723KBTS": "The Fashionisto",
  "LI-59OLQHLOI3": "The Fashionisto",
  "LI-GBX03A4KNI": "Celeb Spin",
  "LI-EUHWMU5H7R": "Celeb Spin",
  "LI-CXYNLGWVES": "theChive",
  "LI-A1AGKNYJI2": "theChive",
  "LI-L6XVI8TLZH": "theChive",
  "LI-Y7TGYBPXBU": "theChive",
  "LI-A36KO89XPP": "theChive",
  "LI-GQQTJUJ3T5": "theChive",
  "LI-00CAW76T8R": "theChive",
  "LI-X7K38QF5M6": "theChive",
  "LI-8Y3Y6JP5CC": "theChive",
  "LI-DX2HCTGQMF": "theChive",
  "LI-453VWBAJ69": "Grooveshark",
  "LI-IHX63RQWN4": "Grooveshark",
  "LI-OTDT2WFIEO": "I Can Has Cheezburger",
  "LI-OCOWS0IOBR": "I Can Has Cheezburger",
  "LI-SKHLR447TS": "I Can Has Cheezburger",
  "LI-CD2KPYXTO5": "I Can Has Cheezburger",
  "LI-02KSPHCXEU": "I Can Has Cheezburger",
  "LI-KWTWCPG71H": "Sneakhype",
  "LI-90K16MP1G4": "Sneakhype",
  "LI-45O9OZ69WL": "Sneakhype",
  "LI-6KQ4HJWNQC": "Sneakhype",
  "LI-HHZMUMIIRL": "Sneakhype",
  "LI-22AVZ8RGLS": "Sneakhype",
  "LI-XVA6DCUQLR": "Sneakhype",
  "LI-5MSOWIK18R": "Sneakhype",
  "LI-9ZWAI56YY5": "Sneakhype",
  "LI-1HYDU3MMAC": "Sneakhype",
  "LI-17K4LGCU46": "Sneakhype",
  "LI-N26OQW0DYT": "Sneakhype",
  "LI-3X696NMKGZ": "Sneakhype",
  "LI-JVY0ZI1XV3": "Sneakhype",
  "LI-EH4TZV0EDA": "StashedBoxes",
  "LI-Z3KXZSWQ5A": "StashedBoxes",
  "LI-SQA9UI84S5": "StashedBoxes",
  "LI-CS5AKARQ0Q": "StashedBoxes",
  "LI-TNZXAOC30C": "StashedBoxes",
  "LI-M2IBUZQDGA": "StashedBoxes",
  "LI-ZEPTWJZYG2": "StashedBoxes",
  "LI-UN6W8NIS17": "StashedBoxes",
  "LI-MXX3OUEYGI": "StashedBoxes",
  "LI-IUEBEDEC6I": "StashedBoxes",
  "LI-W62FURGI1I": "StashedBoxes",
  "LI-O8XNX66GIW": "StashedBoxes",
  "LI-SDFAEG8HV9": "Grooveshark",
  "LI-YIOM2O9MIX": "Grooveshark",
  "LI-CXJMV8B82X": "Grooveshark",
  "LI-21HEUYDWYV": "Grooveshark",
  "LI-244VID2JHE": "Grooveshark",
  "LI-AUOK3W9J0G": "Grooveshark",
  "LI-D6DF1S8RSF": "Grooveshark",
  "LI-THXPJOK2ZB": "Grooveshark",
  "LI-W5XYK3G8VU": "I Can Has Cheezburger",
  "LI-X9LIFNO0WE": "I Can Has Cheezburger",
  "LI-YMEQDFH1F3": "I Can Has Cheezburger",
  "LI-C9HT81OZYY": "I Can Has Cheezburger",
  "LI-EQKQNWEU4E": "I Can Has Cheezburger",
  "LI-DD9IIX173E": "Forbes",
  "LI-WBW4OGXP01": "Forbes",
  "LI-9R18H1Y1WR": "Forbes",
  "LI-I8KUNNXDHG": "Forbes",
  "LI-3Q2A7S5N7I": "Forbes",
  "LI-1J353BV8W5": "Forbes",
  "LI-T1DRPZEZQF": "Forbes",
  "LI-I3LODE8H0F": "Forbes",
  "LI-GPH939RXTM": "Forbes",
  "LI-5EKDCQFXL1": "Forbes",
  "LI-2URNC2AM6E": "Forbes",
  "LI-EER9Y367AY": "Forbes",
  "LI-YQL564T42E": "Forbes",
  "LI-U9F7MGD8KQ": "Forbes",
  "LI-AGRC0KEE2D": "Forbes",
  "LI-R8BZ22HUFA": "Forbes",
  "LI-QXBKBPZYMO": "Forbes",
  "LI-XSW5A68FRM": "Forbes",
  "LI-7AR1U3ZJVA": "Forbes",
  "LI-4AR2AYBB9X": "Forbes",
  "LI-XDNFHDPFCR": "RantSports",
  "LI-GWHP757UTT": "RantSports",
  "LI-BI8M9BLSH2": "RantSports",
  "LI-UQQGTSVTCS": "RantSports",
  "LI-MUEAJNLMX0": "RantSports",
  "LI-CILXPJCT1A": "USA TODAY Sports Media Group",
  "LI-PQJ4Y2HXCA": "USA TODAY Sports Media Group",
  "LI-L56O1NXVN2": "USA TODAY Sports Media Group",
  "LI-IDRILPN194": "USA TODAY Sports Media Group",
  "LI-8GGSWA2HZK": "Conde Nast Collections",
  "LI-CSYW2Q2E3C": "Forbes",
  "LI-LYFB3HO0XZ": "Forbes",
  "LI-1HCB08IRLC": "Conde Nast Collections",
  "LI-QR1MLTCISM": "Adrants",
  "LI-ZTZGNZ73UF": "Adrants",
  "LI-H0XCN151IQ": "Adrants",
  "LI-NC68BPKGFO": "Small Business Trends",
  "LI-6XIYP2FFA5": "Small Business Trends",
  "LI-C3T1J5PYQQ": "BizSugar",
  "LI-QPOGYINX8K": "BizSugar",
  "LI-KUY3N73I1T": "OTCMarkets",
  "LI-LKQW3UDKZY": "OTCMarkets",
  "LI-TN17C3RIXE": "OTCMarkets",
  "LI-9VO28HXJSP": "OTCMarkets",
  "LI-R4IV3B8GM1": "Forbes",
  "LI-347SNPONPK": "Forbes",
  "LI-DUI3IXZOTT": "InnovationExcellence",
  "LI-UOODJB1Z07": "InnovationExcellence",
  "LI-7XAO4VZANU": "InnovationExcellence",
  "LI-5ZN54XR9YL": "Adweek",
  "LI-1AJS3R7GJI": "Adweek",
  "LI-I2QMRFH0KE": "Adweek",
  "LI-4JG4X8BSP5": "Adweek",
  "LI-1R5FB67665": "Mashable",
  "LI-6ASY1SAFQW": "Mashable",
  "LI-DVVDHK3TSJ": "Entrepreneur",
  "LI-4G067XJCHL": "Entrepreneur",
  "LI-RZPHVI0K34": "Entrepreneur",
  "LI-83OHXWM0JQ": "Entrepreneur",
  "LI-R9TIRE8UI8": "Entrepreneur",
  "LI-93CNM4GMZU": "Entrepreneur",
  "LI-RT4GLG1PZR": "Entrepreneur",
  "LI-KG86NHPQHK": "Entrepreneur",
  "LI-3ECXJFTZQT": "Entrepreneur",
  "LI-SUMTOW43TQ": "Entrepreneur",
  "LI-QU7EE9IDS3": "Entrepreneur",
  "LI-CUPVLQ62EE": "Entrepreneur",
  "LI-MOBX970W6M": "The Washington Times",
  "LI-T6C6BZB7HL": "The Washington Times",
  "LI-KNRS9E8UNL": "The Washington Times",
  "LI-ZM53NII54U": "The Washington Times",
  "LI-WT9U8UHC1A": "The Washington Times",
  "LI-XP57N4F0HH": "The Washington Times",
  "LI-6T3JO2D7KG": "The Washington Times",
  "LI-9GNY3PRD3F": "The Washington Times",
  "LI-SLBI9H7L33": "Fashiolista",
  "LI-21643LK9PJ": "Fashiolista",
  "LI-YR2D6FI1CN": "Fashiolista",
  "LI-O1EONLMOMN": "Fashiolista",
  "LI-K3EVM8A4GP": "Fashiolista",
  "LI-VD14HRAR7R": "Mashable",
  "LI-A32NXJH15G": "Mashable",
  "LI-AIETV1CN9T": "Mashable",
  "LI-0QMMJZIY3K": "Mashable",
  "LI-944IHQUI2E": "Serious Eats",
  "LI-T44P0UMU33": "Serious Eats",
  "LI-ZGV0Y8HPQD": "Serious Eats",
  "LI-NMMYNFGQ8D": "Gawker",
  "LI-TP2AA9YYDT": "Dwell",
  "LI-ND9VQ6AXGV": "Dwell",
  "LI-OMD4FSD5XH": "Dwell",
  "LI-ZMRBZT231K": "Dwell",
  "LI-JUX71BD1Y9": "Forbes",
  "LI-SWLIRJTN08": "Forbes",
  "LI-XO02H95GG7": "Forbes",
  "LI-Z6C2HMVZY1": "Forbes",
  "LI-7YJ8OUF6MR": "Conde Nast Collections",
  "LI-9O7I5E4SBZ": "Conde Nast Collections",
  "LI-541Z36WLFF": "The New York Times",
  "LI-KDR7TAVR0Q": "The New York Times",
  "LI-HMJR3YSLWH": "The New York Times",
  "LI-BQZT326WIL": "The New York Times",
  "LI-MFBEMR4HME": "The New York Times",
  "LI-S795TNCU2Q": "The New York Times",
  "LI-WSFKYMO8F7": "The New York Times",
  "LI-X6HC6ISGTA": "The New York Times",
  "LI-OOIGC12VL7": "The New York Times",
  "LI-YD6MUUJXNP": "The New York Times",
  "LI-62DS99K1AL": "The New York Times",
  "LI-LWYBHSQMCQ": "The New York Times",
  "LI-O7GCESD3K3": "The New York Times",
  "LI-7NI1IILWYB": "The New York Times",
  "LI-CJIFUX6JDA": "The New York Times",
  "LI-4DQ6TBYP8W": "theCHIVE",
  "LI-BANXKYMFXN": "theCHIVE",
  "LI-PVARD2AUR3": "Fashiolista",
  "LI-XDYWCDUCYP": "Fashiolista",
  "LI-CLRBPNOFYI": "stylegawker",
  "LI-0N4LHNCP8A": "stylegawker",
  "LI-OBS62IEX79": "stylegawker",
  "LI-WWZHDD5MGN": "We Heart It",
  "LI-H5OG4ZQZCU": "We Heart It",
  "LI-JUW04DZV2I": "We Heart It",
  "LI-55RQA4SKNH": "Radaronline",
  "LI-6YUF45AD9Y": "Radaronline",
  "LI-6UOUT1GWB3": "Radaronline",
  "LI-8G06UKP5FF": "Overstock.com",
  "LI-13KKXMXQKQ": "Overstock.com",
  "LI-SASN2N5U3D": "Overstock.com",
  "LI-ED2M6FEGPP": "Forbes",
  "LI-0QDQTJS27F": "Forbes",
  "LI-O5BR862XF5": "Forbes",
  "LI-4WJSXVEARQ": "Forbes",
  "LI-Q0WCGOI8S8": "Forbes",
  "LI-KDL6WODMH0": "Conde Nast Collections",
  "LI-LEF3QUSN9T": "Conde Nast Collections",
  "LI-XRN41FVZ9S": "Conde Nast Collections",
  "LI-YN2GUYM9WV": "The New York Times",
  "LI-RZLEAMZF96": "The Rising Hollywood",
  "LI-29MKBROU3Q": "The Rising Hollywood",
  "LI-ADLZC54DJU": "Conde Nast Collections",
  "LI-WCPUWIU67Q": "Conde Nast Collections",
  "LI-GBRZ8JODQS": "Conde Nast Collections",
  "LI-RMYTUCZMG8": "Conde Nast Collections",
  "LI-KKF2CPDG20": "Conde Nast Collections",
  "LI-WINY3RDJEW": "Conde Nast Collections",
  "LI-NU3JYE7XOV": "Conde Nast Collections",
  "LI-74VP56X1HI": "Conde Nast Collections",
  "LI-68F1BCRDRV": "Conde Nast Collections",
  "LI-ACDKR66WUB": "Conde Nast Collections",
  "LI-E2SNROSNF5": "Conde Nast Collections",
  "LI-K0JUTP1AY5": "Conde Nast Collections",
  "LI-GTPUMI1MVY": "Conde Nast Collections",
  "LI-ZQ8D5L9OTJ": "Conde Nast Collections",
  "LI-HPVHE2GTN1": "Conde Nast Collections",
  "LI-3CYKSGLS5S": "Conde Nast Collections",
  "LI-KXRUX083QL": "Conde Nast Collections",
  "LI-VNIJJAE0UG": "Conde Nast Collections",
  "LI-7BTBDUUSQC": "Conde Nast Collections",
  "LI-6O31S9SKTQ": "Conde Nast Collections",
  "LI-WBR4MSD24X": "Conde Nast Collections",
  "LI-URNCG9AETE": "Conde Nast Collections",
  "LI-TQPJP6XXRP": "Conde Nast Collections",
  "LI-6LVBL0DZH8": "Conde Nast Collections",
  "LI-B4I85KS153": "The Washington Times",
  "LI-XT53EFBM55": "The Washington Times",
  "LI-SNDJTJXV6N": "Gigaom",
  "LI-AVEJY8N11W": "VentureBeat",
  "LI-EFA6UGFOOE": "VentureBeat",
  "LI-DXC0BG80MW": "VentureBeat",
  "LI-1DDT1JZAYF": "VentureBeat",
  "LI-7LQ4V8DIO7": "VentureBeat",
  "LI-M8XJ95SBK5": "VentureBeat",
  "LI-ERAECUDKFF": "The Atlantic",
  "LI-9S3T8NOF7R": "The Atlantic",
  "LI-EV4LRLVG1Y": "The Atlantic",
  "LI-YKA9AG7TET": "The Atlantic",
  "LI-EJMOSC2MRC": "The Atlantic",
  "LI-VH69BCBXTY": "The Atlantic",
  "LI-OFL8COI86M": "Chicago Tribune",
  "LI-BJFJAB9GA4": "Chicago Tribune",
  "LI-AVBP29G1FZ": "Chicago Tribune",
  "LI-ZZTS6S2DRP": "Chicago Tribune",
  "LI-OFST2KWK9E": "Chicago Tribune",
  "LI-1WC6QTFU5D": "The Washington Post",
  "LI-BUH2ROEQTA": "The Washington Post",
  "LI-IOLSY36E9L": "The Economist",
  "LI-79SNDCR5UL": "Valet.",
  "LI-9QWFSBTXLH": "Recipe Corner",
  "LI-EPEML0XHD1": "Recipe Corner",
  "LI-VUWY0LVBXL": "Recipe Corner",
  "LI-2J0B5YZP4I": "Recipe Corner",
  "LI-RC1EZBEMU8": "Recipe Corner",
  "LI-DOVEKGTL3D": "Conde Nast Collections",
  "LI-BYXW19CKS3": "Conde Nast Collections",
  "LI-E7O22Y3KWO": "Conde Nast Collections",
  "LI-T5A9SZYWGA": "The Washington Post",
  "LI-FY5NO989EQ": "The Washington Post",
  "LI-N1YLZ1GN7S": "Conde Nast Collections",
  "LI-37BMZ54E2P": "Conde Nast Collections",
  "LI-E1WR8Y0E8O": "Conde Nast Collections",
  "LI-XVJ6O6TXAV": "Conde Nast Collections",
  "LI-53CYMO5PJE": "Fashion Gone Rogue",
  "LI-YK4Z9PFZ24": "Fashion Gone Rogue",
  "LI-C9CFERI7NT": "Fashion Gone Rogue",
  "LI-PI8WYHSQ5M": "Fashion Gone Rogue",
  "LI-H8EU2NEWXY": "Fashion Gone Rogue",
  "LI-55NVFMON50": "Fashion Gone Rogue",
  "LI-8CZRT6G1V9": "Conde Nast Collections",
  "LI-1PPSX7Y1AR": "Fashion Gone Rogue",
  "LI-BQ6Q9ABVPH": "Fashion Gone Rogue",
  "LI-53NMIKP4AK": "Fashion Gone Rogue",
  "LI-T7M3ISGFDC": "Fashion Gone Rogue",
  "LI-I0PDQW1C42": "Fashion Gone Rogue",
  "LI-2VTJ659SJ5": "Fashion Gone Rogue",
  "LI-Z99U6Y7A8Y": "Fashion Gone Rogue",
  "LI-KLGS88UH6R": "Fashion Gone Rogue",
  "LI-KYXDZCDM13": "Fashion Gone Rogue",
  "LI-1LFX6T0E06": "Fashion Gone Rogue",
  "LI-ICAE2OKD7N": "Fashion Gone Rogue",
  "LI-4SE16WTKYE": "Fashion Gone Rogue",
  "LI-LRQXGI18R6": "Fashiolista",
  "LI-Q8AJU84XJE": "Fashiolista",
  "LI-HASFRIZGAK": "The Rising Hollywood",
  "LI-LHFG5WH8IO": "The Rising Hollywood",
  "LI-47ZH1PBNAV": "Forbes",
  "LI-G6R5ZBSH65": "Forbes",
  "LI-GPFIFWFQQN": "Wired",
  "LI-7F46T1SJD3": "Wired",
  "LI-N8BNLTD7KJ": "Wired",
  "LI-3Q8SFGCRBW": "Wired",
  "LI-EU4J5ONA7K": "Wired",
  "LI-YM1YIR41ZV": "Wired",
  "LI-9EENAD7RR6": "Wired",
  "LI-SB63LEGNE3": "Wired",
  "LI-N2Q67HD3WN": "Wired",
  "LI-LG0LZ4VR5D": "Wired",
  "LI-GPPUA7AMMA": "Wired",
  "LI-FZINP60X1E": "Wired",
  "LI-ZB3MHCYCRI": "Conde Nast Collections",
  "LI-AM0XYJYU8Y": "Vanity Fair",
  "LI-MJ0PYZ67PM": "Vanity Fair",
  "LI-Z6KIOAZU5X": "Vanity Fair",
  "LI-CQZSJWEOU4": "Vanity Fair",
  "LI-KTR344CRYK": "Allure",
  "LI-DNI6VJ4V1F": "RantSports",
  "LI-6U9HPGYG77": "RantSports",
  "LI-ZYVE6877SP": "RantChic",
  "LI-ISEFW5EKIP": "RantChic",
  "LI-LON63FSXCH": "RantChic",
  "LI-66MCLY8YX4": "RantChic",
  "LI-G9X9V4BWML": "RantLifestyle",
  "LI-KQ89EOTEQV": "RantLifestyle",
  "LI-5HF9IP6MI3": "Feelgood Style",
  "LI-ZYB9MV3I9L": "Feelgood Style",
  "LI-RIZZS4J07J": "Vibrant Wellness Journal",
  "LI-77SHFGN07Y": "Vibrant Wellness Journal",
  "LI-OC17XF84CN": "Allure",
  "LI-LI1T0WXISQ": "Allure",
  "LI-JKYK545FQQ": "GQ",
  "LI-586SOUKR8S": "Details",
  "LI-UDY51QN47Y": "Temptalia",
  "LI-98DOH1VWHY": "Temptalia",
  "LI-AB4L9SIY6F": "stylegawker",
  "LI-8VWH9WBT9B": "Fashion Gone Rogue",
  "LI-Z017X1RRGU": "Fashion Gone Rogue",
  "LI-QS3UXMCODT": "The Fashionisto",
  "LI-51CRQV1BSS": "The Fashionisto",
  "LI-8GUEBGOKPC": "Tribal Football",
  "LI-8GPZL8WIAC": "Tribal Football",
  "LI-UHRPD1O674": "Fashiolista",
  "LI-74BD5T95PH": "Fashiolista",
  "LI-DQIQH366AK": "USA TODAY Sports Media Group",
  "LI-HT8NVW70U5": "Deadspin",
  "LI-PJZWKHUFH5": "Deadspin",
  "LI-D309GXEYAO": "The Knot",
  "LI-OPIDDBC2XD": "The Knot",
  "LI-SD4OELA0HY": "The Knot",
  "LI-OKF3X4W0F1": "The Knot",
  "LI-JCVMBM8214": "The Knot",
  "LI-GPEJ9WSDX8": "The Nest",
  "LI-9YK1GH3L1G": "The Nest",
  "LI-NYSKU5WDW1": "The Bump",
  "LI-ZVEIOREVZ6": "The Bump",
  "LI-ONCXXOWUVE": "The Bump",
  "LI-L61K3MRUH1": "The Bump",
  "LI-0BSQFBPMCI": "Rolling Stone",
  "LI-HYV88CW07Y": "Rolling Stone",
  "LI-UF8V9QBA16": "Fashion Gone Rogue",
  "LI-CAM3A2IN3Z": "Fashion Gone Rogue",
  "LI-QGFG2W53SH": "Fashion Gone Rogue",
  "LI-25O71D8LJT": "Forbes",
  "LI-3KBLI4LR5L": "HipHopWired",
  "LI-36SA8WNQ26": "HipHopWired",
  "LI-8B4ATA9NWP": "HipHopWired",
  "LI-B9XTHJKI9H": "HipHopWired",
  "LI-8VGOTC5BOE": "HipHopWired",
  "LI-PE8PCN5X18": "HipHopWired",
  "LI-SPZHCS53TY": "HipHopWired",
  "LI-OIFESMJ6GN": "HipHopWired",
  "LI-LIMI0TT8IL": "MSN",
  "LI-TIXVS25LCI": "MSN",
  "LI-IU2ZT7ZQKW": "MSN",
  "LI-CVSD3WYX4L": "MSN",
  "LI-F1OWXJ1DU6": "Conde Nast Collections",
  "LI-LQVA42TTY4": "Conde Nast Collections",
  "LI-GEBMO5ZR11": "The New York Times",
  "LI-ZYHC7K46IM": "Conde Nast Collections",
  "LI-3CMVWUT4T0": "Conde Nast Collections",
  "LI-47H7ZFQ415": "Conde Nast Collections",
  "LI-8UI0S9R6C9": "Conde Nast Collections",
  "LI-QLIE3WTRHW": "Conde Nast Collections",
  "LI-5KT3R3Z9L9": "Conde Nast Collections",
  "LI-3KI5RMGUDE": "Conde Nast Collections",
  "LI-DET8XNAXF5": "Conde Nast Collections",
  "LI-QVPSQ6MC4U": "The Economist",
  "LI-LW9JNTZ9O8": "The Economist",
  "LI-9L0FPI6G2F": "The Economist",
  "LI-ZVWM2OTQDP": "The Economist",
  "LI-K07J4TJQV2": "The Economist",
  "LI-IMWOM29TTL": "The Economist",
  "LI-5LFZ20J3JY": "The Washington Post",
  "LI-WBB3NJ3BCV": "The Washington Post",
  "LI-LAB292ZFJI": "The Washington Post",
  "LI-2IA4BUOPTU": "The Washington Post",
  "LI-DYNTPRYO0N": "The Washington Post",
  "LI-JWERI9BELF": "The Washington Post",
  "LI-KM7QR4QSF1": "The Washington Post",
  "LI-1BGBPQ49RM": "The Washington Post",
  "LI-AE1DKFJMNW": "Thought Catalog",
  "LI-ET5BJYHO6T": "Thought Catalog",
  "LI-6TVHQZ9QS0": "Thought Catalog",
  "LI-0DDYJC0MN3": "Thought Catalog",
  "LI-3AVOHXYWB9": "Thought Catalog",
  "LI-684OH7R17U": "Thought Catalog",
  "LI-L4JO235J13": "Thought Catalog",
  "LI-P7L8PNJAO5": "The Daily Beast",
  "LI-J1QF72VE63": "The Daily Beast",
  "LI-XU3GPAAHF8": "Thought Catalog",
  "LI-RHX7ZFXEWT": "Thought Catalog",
  "LI-PWNWDM413F": "Thought Catalog",
  "LI-U2UT8YCN5Q": "Thought Catalog",
  "LI-WAYBB0JA5T": "Thought Catalog",
  "LI-PW709NHAVJ": "Thought Catalog",
  "LI-N51JN0JB4G": "Thought Catalog",
  "LI-SHW9M6ISLK": "Thought Catalog",
  "LI-IZMPHS21IY": "Thought Catalog",
  "LI-3N88ST2PMU": "Thought Catalog",
  "LI-QX8EFMT4X0": "Thought Catalog",
  "LI-M1DLDKVNMR": "Thought Catalog",
  "LI-P0L6V6NE0L": "The Atlantic",
  "LI-CEX0BPI77C": "The Atlantic",
  "LI-HC5SU04BL8": "The Atlantic",
  "LI-C1XBA7MARR": "The Atlantic",
  "LI-QHQ3LJOXJS": "The Atlantic",
  "LI-NDRV6VBEXX": "The Daily Beast",
  "LI-H2OS5ECWVS": "The Daily Beast",
  "LI-D370KS5O7N": "The Daily Beast",
  "LI-CTYCGY784H": "The Daily Beast",
  "LI-VDJBFCCLHW": "The Daily Beast",
  "LI-LL7EMUALD1": "The Daily Beast",
  "LI-UGYI99YX29": "The Daily Beast",
  "LI-KSJVBZ5PS9": "The Daily Beast",
  "LI-U1TSH0VE4E": "The Daily Beast",
  "LI-NJ7D4WNI4N": "The New York Times",
  "LI-DUPS0EV5BM": "The New York Times",
  "LI-HOE9MGULAC": "The New York Times",
  "LI-EK4WSM6EHD": "The New York Times",
  "LI-ZVG2KUA75X": "The Atlantic",
  "LI-FOOTQBZA6P": "The Atlantic",
  "LI-9X670BUPSX": "The Atlantic",
  "LI-BWJY5Z2A1C": "HipHopWired",
  "LI-5GXOU4007S": "HipHopWired",
  "LI-CWO6OUXA6N": "HipHopWired",
  "LI-980KQHENE9": "Altsounds.com",
  "LI-90RNCNKAHK": "Altsounds.com",
  "LI-QCOL3TYPKM": "Altsounds.com",
  "LI-6BFUSDYRAX": "Oh My Rockness NYC",
  "LI-67PJ04CVP3": "Oh My Rockness NYC",
  "LI-1EA1JS2SFX": "Oh My Rockness NYC",
  "LI-HLHKJXEC2R": "Oh My Rockness NYC",
  "LI-G8V60ZQL4T": "Oh My Rockness NYC",
  "LI-07VLEX1FF3": "Oh My Rockness NYC",
  "LI-XGRFW0SUEH": "Oh My Rockness NYC",
  "LI-7MJ52Z6D1H": "Oh My Rockness NYC",
  "LI-MZCCFVK9HT": "Oh My Rockness NYC",
  "LI-V8OU1CW4ZK": "Oh My Rockness NYC",
  "LI-YIKKVQ44F2": "Oh My Rockness NYC",
  "LI-GJ91REGMEH": "Oh My Rockness NYC",
  "LI-4AUMK5FBJ6": "Oh My Rockness NYC",
  "LI-FA247A11E1": "Oh My Rockness NYC",
  "LI-T6B5K5YJA7": "Oh My Rockness NYC",
  "LI-1LC66M3EBB": "Oh My Rockness NYC",
  "LI-4PD77RSRHZ": "Oh My Rockness NYC",
  "LI-93CQYGM1XZ": "Shape",
  "LI-T88WOT0RNT": "Shape",
  "LI-YRDIWQNOP8": "Shape",
  "LI-T4TNCHUGI6": "Overstock.com",
  "LI-UODD8Z36S4": "Overstock.com",
  "LI-X0EKP5EQ8M": "Overstock.com",
  "LI-NMBELW82DL": "Overstock.com",
  "LI-W7H1MVHKH6": "Overstock.com",
  "LI-YE2GO6J177": "Overstock.com",
  "LI-V1LH7J9UOY": "Allure",
  "LI-2OW9TEJMCI": "Allure",
  "LI-OBZMY8MG30": "Allure",
  "LI-LXW87040HD": "Conde Nast Collections",
  "LI-JL2KTA35AM": "eHow",
  "LI-C79OV7E1UK": "Livestrong",
  "LI-16SNNFZ9H8": "Livestrong",
  "LI-1PMVH3UD7K": "Livestrong",
  "LI-X5S3IDSX14": "Livestrong",
  "LI-WR3K1OOZKI": "Livestrong",
  "LI-1CSHICQATO": "Livestrong",
  "LI-AD7GW99RBX": "Rolling Stone",
  "LI-CEPJXNTWGX": "Rolling Stone",
  "LI-7MPTQW7J4M": "Rolling Stone",
  "LI-MNOZ3UDYLG": "The Knot",
  "LI-GZLTY4XI8Z": "The Knot",
  "LI-DOKP5N9NN3": "The Knot",
  "LI-THS9R523R7": "The Knot",
  "LI-YKGXGC3MSQ": "The Bump",
  "LI-8DBSDSJVJL": "The Bump",
  "LI-YN1ET33SRD": "The Bump",
  "LI-MH756XQFWJ": "The Bump",
  "LI-7W6GHDLA3U": "The Bump",
  "LI-991TFZ06T4": "The Nest",
  "LI-3ZF8HPQDO1": "The Nest",
  "LI-LA5YCASQ2S": "Radaronline",
  "LI-1NNEFRPPYB": "Radaronline",
  "LI-8GB27WGU2S": "W Magazine",
  "LI-5MSR33UDT7": "W Magazine",
  "LI-G3BW7AYNXW": "W Magazine",
  "LI-W7BNCS1XT8": "Conde Nast Collections",
  "LI-RRYKST46GL": "New York Post",
  "LI-HBG950IFYK": "New York Post",
  "LI-X91YVW9I55": "New York Post",
  "LI-U1IMVZIYB1": "New York Post",
  "LI-0D1E84Z1B6": "New York Post",
  "LI-4TBZK9JX0Q": "New York Post",
  "LI-NQ1CCS77HM": "New York Post",
  "LI-Z3W2NB4Q9A": "New York Post",
  "LI-L45P2NEXK5": "YouBeauty",
  "LI-4HQCBBJBEK": "YouBeauty",
  "LI-ILRT6PBPY7": "YouBeauty",
  "LI-G1K5KE4VLZ": "YouBeauty",
  "LI-KYW5MX1MEZ": "YouBeauty",
  "LI-503BYE0LQY": "YouBeauty",
  "LI-SR8J2ZVTNV": "YouBeauty",
  "LI-YHW081KEV5": "YouBeauty",
  "LI-2Q77V59LF1": "YouBeauty",
  "LI-9UDF9MLG4K": "YouBeauty",
  "LI-A9P2NQVM2Y": "YouBeauty",
  "LI-6KWQQK0EG9": "YouBeauty",
  "LI-NNKN1992UU": "YouBeauty",
  "LI-9T11CV3L67": "YouBeauty",
  "LI-ITXU0SU993": "YouBeauty",
  "LI-MPQ96MWJDN": "YouBeauty",
  "LI-IFJBNRYHHJ": "Shape",
  "LI-F0QKTYKBFU": "Shape",
  "LI-KC7A9WW80G": "Shape",
  "LI-2XYBPIM2G4": "Rolling Stone",
  "LI-DRL95SZU02": "New York Post",
  "LI-K4AEPN2JD3": "New York Post",
  "LI-TUZKILD54I": "New York Post",
  "LI-XFXWYEU8ST": "New York Post",
  "LI-LGCRFWCOSP": "New York Post",
  "LI-4B1MVDSCZN": "New York Post",
  "LI-6QXT3PCBDH": "New York Post",
  "LI-U7NTENS1ZX": "New York Post",
  "LI-H3NOS80UVK": "The New York Times",
  "LI-J6W4R7FOVB": "The New York Times",
  "LI-YVOYENND4V": "National Review ",
  "LI-3ID10SAOU9": "The Daily Caller",
  "LI-3MRPWVE8LQ": "The Daily Caller",
  "LI-O72ZR0L9CK": "The Daily Caller",
  "LI-V5J55QXWH1": "The Daily Caller",
  "LI-7ZRIL2Z3G0": "The New York Times",
  "LI-CFP2JP2HS2": "The New York Times",
  "LI-6LDDG3KF91": "National Review ",
  "LI-4O1IPMI4Z2": "The New York Times",
  "LI-Q5KQN4K9JJ": "The New York Times",
  "LI-99IAADEFN4": "The New York Times",
  "LI-W93V1I7NYS": "The New York Times",
  "LI-O9AXIB7CLM": "USA TODAY Sports Media Group",
  "LI-CCC0Y3404I": "USA TODAY Sports Media Group",
  "LI-CVWF6MDHMN": "USA TODAY Sports Media Group",
  "LI-YR8UG8A214": "USA TODAY Sports Media Group",
  "LI-9OPD3YRIPU": "The Washington Times",
  "LI-J8C38HLX3M": "The Washington Times",
  "LI-0119GK1KHU": "The Washington Times",
  "LI-WS8F3GPN6L": "The Washington Times",
  "LI-YITNASMZ8B": "Allure",
  "LI-6HSLE2Y36M": "Allure",
  "LI-AIBBH4B7NE": "Architectural Digest",
  "LI-ENXHGETQW1": "Architectural Digest",
  "LI-78RR1VJQC2": "USA TODAY Sports Media Group",
  "LI-6BWCZVBIQ0": "YouBeauty",
  "LI-31AEX4YUMZ": "New York Post",
  "LI-WH7G3IKH3T": "New York Post",
  "LI-1SMHWDDE1S": "New York Post",
  "LI-KMIICG6D7B": "New York Post",
  "LI-UDE0BPO9JB": "New York Post",
  "LI-1C828XV78F": "New York Post",
  "LI-KA7XF7VUGA": "New York Post",
  "LI-GVYDMU4DI0": "New York Post",
  "LI-CEC029DKIX": "Trulia",
  "LI-UPA0VM4H05": "Trulia",
  "LI-6QHD6D6PHR": "YouBeauty",
  "LI-SDB43D35FY": "YouBeauty",
  "LI-UJSO16HLIH": "Grooveshark",
  "LI-MSN3AIFANW": "Grooveshark",
  "LI-1QLH02M4CY": "The Washington Post",
  "LI-5Y9M0TU6KH": "National Review ",
  "LI-EFOIYNV68F": "National Review ",
  "LI-2UDBKV9KIO": "National Review ",
  "LI-Z54Z0N7RZU": "The New York Times",
  "LI-QOG1YACNE7": "The New York Times",
  "LI-FDU3RF6G1B": "The New York Times",
  "LI-OSRKXNMWSC": "The New York Times",
  "LI-0U0IF94TRL": "The New York Times",
  "LI-UTMJHGSU0B": "The New York Times",
  "LI-6SR0RL3HOS": "The New York Times",
  "LI-QCUD2NDB9Y": "The New York Times",
  "LI-SO4J6RWH81": "The New York Times",
  "LI-OFOC9ST46M": "The New York Times",
  "LI-3B1K9KC8IX": "The New York Times",
  "LI-FVWJTTRBIM": "The New York Times",
  "LI-WWG10ZPAZF": "The New York Times",
  "LI-HEX1VR4E1E": "The New York Times",
  "LI-F533INYEL0": "The New York Times",
  "LI-LYI50E3PO3": "The New York Times",
  "LI-UBZA86EE0W": "The New York Times",
  "LI-Y3361N7AUP": "The New York Times",
  "LI-KPBHWLBO3K": "The New York Times",
  "LI-VPME432NR6": "The New York Times",
  "LI-9HP6610A5E": "The New York Times",
  "LI-LV1X63TJZZ": "The New York Times",
  "LI-3WZ6VJBZNX": "The New York Times",
  "LI-USVGQT5TVT": "The New York Times",
  "LI-C19ZTSIMTE": "The New York Times",
  "LI-RBAGWP0ZFU": "The New York Times",
  "LI-7PNGRL1SWJ": "The New York Times",
  "LI-PZ0ULSZBTI": "The New York Times",
  "LI-YWDDQY1NUG": "The New York Times",
  "LI-U4JGF2HD3Q": "The New York Times",
  "LI-5RACFLDD61": "The New York Times",
  "LI-BBNIRF9TTG": "The New York Times",
  "LI-9YMI8UP6KZ": "The New York Times",
  "LI-RHBIEA181P": "The New York Times",
  "LI-CEQ45PHU26": "The New York Times",
  "LI-E24U49DTFK": "The New York Times",
  "LI-PPUZVTWNQO": "The New York Times",
  "LI-7CML64451V": "The New York Times",
  "LI-OAME9XE0NV": "The New York Times",
  "LI-ZPDU1PTD0X": "The New York Times",
  "LI-Z36WR10B23": "The New York Times",
  "LI-AOSAGEB0EW": "The New York Times",
  "LI-4Q2JI2UUFF": "Seeking Alpha",
  "LI-RRHN322FFM": "Conde Nast Collections",
  "LI-EWK3TRGF81": "Conde Nast Collections",
  "LI-9RU4RV2BGS": "Conde Nast Collections",
  "LI-WFP2SX0FZ8": "Conde Nast Collections",
  "LI-37MGRSFJME": "W Magazine",
  "LI-VPFVPDKZIH": "Details",
  "LI-EOPAXI806O": "GQ",
  "LI-R5TRW9LR5C": "Vanity Fair",
  "LI-D0NN3NJXYO": "Style.com",
  "LI-5CAEBEG4H8": "Martini Inc.",
  "LI-PXBSO2V70W": "Martini Inc.",
  "LI-3VNXS2EH2H": "Martini Inc.",
  "LI-ANNA1W5MQ0": "Martini Inc.",
  "LI-Q9BUK83ZH0": "Martini Inc.",
  "LI-OUDS080A4I": "USA TODAY Sports Media Group",
  "LI-GAKAPZ9TS0": "USA TODAY Sports Media Group",
  "LI-6DNBJPUOAF": "USA TODAY Sports Media Group",
  "LI-GKUG6YIW0M": "USA TODAY Sports Media Group",
  "LI-B3YOYFL4U8": "USA TODAY Sports Media Group",
  "LI-WQIGJTVW93": "USA TODAY Sports Media Group",
  "LI-EPIQ5AHZM8": "USA TODAY Sports Media Group",
  "LI-SC8Y6IVPE6": "USA TODAY Sports Media Group",
  "LI-TPHFHJUS1J": "USA TODAY Sports Media Group",
  "LI-ZMFZBBSM5L": "USA TODAY Sports Media Group",
  "LI-4CTN86J8CK": "Bloomberg",
  "LI-IV5BFJDIE6": "Complex",
  "LI-95R3TW5BK7": "Complex",
  "LI-G6SFLQUE35": "Complex",
  "LI-BTI6S0JX3H": "Complex",
  "LI-CD57SVGCL8": "Martini Inc.",
  "LI-BCUUTCDZJG": "Martini Inc.",
  "LI-EKCZZDMKDL": "Martini Inc.",
  "LI-CX320KLCQ6": "Martini Inc.",
  "LI-NNIK5JZPBS": "Martini Inc.",
  "LI-ACEES7AIKH": "Martini Inc.",
  "LI-44G5AVO2EU": "Martini Inc.",
  "LI-1QWSOCGV49": "Martini Inc.",
  "LI-G0XPKIHLYQ": "Martini Inc.",
  "LI-YRDT66JCSY": "NY Daily News",
  "LI-3DYZ2KQF8W": "USA TODAY Sports Media Group",
  "LI-ZFBP5ZE85S": "USA TODAY Sports Media Group",
  "LI-HS6KO2O7BW": "USA TODAY Sports Media Group",
  "LI-TC55FCA9ZM": "Forbes",
  "LI-4O9UKHLU68": "MSN",
  "LI-KS11AYWKG9": "MSN",
  "LI-37UM2AWF6R": "MSN",
  "LI-UIGVGDNPJ7": "MSN",
  "LI-FONOJCC8IK": "MSN",
  "LI-RRNCOZIUYV": "MSN",
  "LI-4W3DVMNJXZ": "MSN",
  "LI-MR852ABZ8H": "MSN",
  "LI-PHHL7DMRJD": "MSN",
  "LI-C68K5S42JU": "MSN",
  "LI-XC4Y2XSKTE": "MSN",
  "LI-XLD83H4ID2": "MSN",
  "LI-FUU80JXE91": "MSN",
  "LI-9THYCSVR5M": "MSN",
  "LI-7TALZJKLWW": "MSN",
  "LI-L51CKH2YTX": "MSN",
  "LI-S6YLAXIHZI": "MSN",
  "LI-KR80L7K1MS": "MSN",
  "LI-WNAAOJHYZM": "MSN",
  "LI-BB2GJPGN3T": "MSN",
  "LI-3DJFWCRKH9": "MSN",
  "LI-L4AIO3L7II": "MSN",
  "LI-1IDZW8DQNM": "MSN",
  "LI-DST9D1QO65": "MSN",
  "LI-0JUM9MSP67": "MSN",
  "LI-NNEWBX48XN": "Outlook",
  "LI-ODU17CS5Z9": "Windows 8",
  "LI-JE4OFKGH8Q": "Windows 8",
  "LI-836HMN5GQW": "Windows 8",
  "LI-7GS2BGQLAL": "Windows 8",
  "LI-PEZPWF9VV9": "The New York Times",
  "LI-UI5WBIDXP9": "The New York Times",
  "LI-4BQ1HWZ7ZL": "The New York Times",
  "LI-ZBCJXV54BK": "The New York Times",
  "LI-75V9VEFQST": "The New York Times",
  "LI-TLXO3F2DS9": "The New York Times",
  "LI-N07MFKTK1H": "The New York Times",
  "LI-32F53BDMT6": "The New York Times",
  "LI-CGJGDZJGXC": "MSN",
  "LI-SFZAAQSQJ6": "MSN",
  "LI-VV1YCCYBCA": "MSN",
  "LI-2ZDR23N4YX": "MSN",
  "LI-WZ6HYXRGVG": "USA TODAY",
  "LI-IPGBJMM23C": "USA TODAY",
  "LI-LOKXD7V99L": "MSN",
  "LI-LB837HN0GY": "MSN",
  "LI-6BTOHAXLXQ": "MSN",
  "LI-ZNKBX6OFPE": "MSN",
  "LI-AC3TKZJ668": "The New York Times",
  "LI-3GXH8DA5WF": "The New York Times",
  "LI-ST7O1S0F5O": "The New York Times",
  "LI-JX0WALLM51": "The New York Times",
  "LI-JPHYVOZ2WE": "The New York Times",
  "LI-A2YA3DSVXE": "The New York Times",
  "LI-DBGXALG9TQ": "The New York Times",
  "LI-WQOK9FOBM5": "The New York Times",
  "LI-M9TKVX6915": "MSN",
  "LI-WNF8RWYYVR": "MSN",
  "LI-3W9127VC9Z": "MSN",
  "LI-OUGH14TMSI": "MSN",
  "LI-48B7XJCCHQ": "MSN",
  "LI-PO16OCWSIN": "MSN",
  "LI-45VKIPD6FF": "MSN",
  "LI-1IJM9VNC8Q": "MSN",
  "LI-WLUCCN815U": "US Weekly",
  "LI-KNWCGR4III": "US Weekly",
  "LI-LPBZ5EY4Y9": "The Daily Caller",
  "LI-L6J3AQBBK8": "The Daily Caller",
  "LI-7WF2MGIBYK": "The Daily Caller",
  "LI-ZYB6JJHBM6": "The Daily Caller",
  "LI-T5ECJYXQCP": "The Daily Caller",
  "LI-ZO55S8UY86": "The Daily Caller",
  "LI-96S6XRE9G9": "The Daily Caller",
  "LI-9ARSDBDIAC": "The Daily Caller",
  "LI-SMKF8VI9R7": "The Daily Caller",
  "LI-WU5XTFNDIJ": "The Daily Caller",
  "LI-P5RRB8EK5X": "The Daily Caller",
  "LI-X229V1KTZZ": "The Daily Caller",
  "LI-V7Y9JFNQIX": "USA TODAY",
  "LI-69GDQJLSBS": "USA TODAY",
  "LI-KUFXQHC4H5": "Business Insider US",
  "LI-STYSS4Y2TS": "Business Insider US",
  "LI-F5OQE2BT71": "Gizmodo",
  "LI-L99F99SZX6": "Gizmodo",
  "LI-MSXASCYJ9D": "AccuWeather",
  "LI-1W7G7ZB03H": "AccuWeather",
  "LI-7K2S42F3ZQ": "io9",
  "LI-9XCZIFAVM1": "Jalopnik",
  "LI-JIPMJCZ21D": "Wired",
  "LI-LJ01RCNW09": "Wired",
  "LI-WMGBHMSAK0": "Jalopnik",
  "LI-R41GCGOHAN": "io9",
  "LI-C3ONLOZ539": "Jalopnik",
  "LI-BPUZP2HEF7": "io9",
  "LI-O05SYPR5PB": "Deadspin",
  "LI-Q8K45ZYF99": "Kotaku",
  "LI-Y1MFD52CQP": "io9",
  "LI-NEJ3OU5MLL": "Rolling Stone",
  "LI-XL6D65PLSQ": "Rolling Stone",
  "LI-7LJZ4YSLFY": "Rolling Stone",
  "LI-IW1RY5MNID": "Men's Journal",
  "LI-8DN6IOT8GZ": "Men's Journal",
  "LI-UGSS263YBK": "Gawker",
  "LI-X2QZ1RJBPU": "The Daily Caller",
  "LI-PL5SGZ3OM3": "The Daily Caller",
  "LI-GHU9QLJ5DY": "The Daily Caller",
  "LI-5VKBI5Y3JK": "The Daily Caller",
  "LI-TNWMRUED35": "The Daily Caller",
  "LI-3XFHHSAKMG": "The Daily Caller",
  "LI-MG112HOPGC": "The Daily Caller",
  "LI-QUPO4OQ2KR": "The Daily Caller",
  "LI-PWGX1RSXMF": "The Daily Caller",
  "LI-5DL812NAN3": "The Daily Caller",
  "LI-UK8YIXKXPJ": "The Daily Caller",
  "LI-0201J69OR6": "The Daily Caller",
  "LI-0TJTIL950K": "Gawker",
  "LI-7DS93I212D": "Deadspin",
  "LI-NUNHGCWZOG": "Martini Inc.",
  "LI-5VM1WCIYIN": "Martini Inc.",
  "LI-D7Q7QOWB60": "Martini Inc.",
  "LI-OWR598Y4H9": "Martini Inc.",
  "LI-0W3IV2IBQP": "Martini Inc.",
  "LI-99QO6GMBGT": "Martini Inc.",
  "LI-ZM8H9122JP": "Martini Inc.",
  "LI-DFURB6O8W1": "Martini Inc.",
  "LI-B0BBMO2Z3Q": "Martini Inc.",
  "LI-VZR54UY6HM": "Martini Inc.",
  "LI-580WQ1AHV0": "Rolling Stone",
  "LI-44X9G11KWZ": "Rolling Stone",
  "LI-64OZ5VKWOK": "Rolling Stone",
  "LI-D1CDBIVQ3D": "Rolling Stone",
  "LI-VBAOZTB002": "Rolling Stone",
  "LI-0JADUQI6O9": "Men's Journal",
  "LI-FCMRWL0XBG": "Men's Journal",
  "LI-F8X0V6NXR7": "Men's Journal",
  "LI-YVIV5I1DF2": "Men's Journal",
  "LI-RFCV77PZR0": "Men's Journal",
  "LI-FLBPB0KSM3": "Rolling Stone",
  "LI-X6YZHU04IH": "Rolling Stone",
  "LI-C7XQP2CUJK": "Rolling Stone",
  "LI-3U41IQ7U5J": "Rolling Stone",
  "LI-N9ZJ607A37": "Rolling Stone",
  "LI-QXM5D6Q8OJ": "Men's Journal",
  "LI-LDK488DIX2": "Men's Journal",
  "LI-FFH7XDCXZY": "Men's Journal",
  "LI-T95347W24X": "Men's Journal",
  "LI-Q28XIBKN7H": "Men's Journal",
  "LI-V33DSWA4NU": "Men's Journal",
  "LI-9L20UH31DO": "Men's Journal",
  "LI-U9IJGU9L02": "Men's Journal",
  "LI-7NRVYP5U0F": "Men's Journal",
  "LI-AB9X0IA2PA": "Men's Journal",
  "LI-8CEPK1I6EQ": "NY Daily News",
  "LI-RUDRNUYJLW": "NY Daily News",
  "LI-4WYSN3S5UL": "Rolling Stone",
  "LI-KSOYD3PPFF": "Rolling Stone",
  "LI-4LQNEQJWWI": "Rolling Stone",
  "LI-PJ3118V8SG": "Rolling Stone",
  "LI-7H4JRGJV9X": "Rolling Stone",
  "LI-1NWUFCUPCA": "The Wall Street Journal",
  "LI-3HF35FHET3": "The Wall Street Journal",
  "LI-E9ON5GISVE": "The Wall Street Journal",
  "LI-B9YDGOZPA0": "The Wall Street Journal",
  "LI-IVSLBGMSUN": "The Wall Street Journal",
  "LI-WQ84QNOSOT": "The Wall Street Journal",
  "LI-ILK88AAGF6": "The Wall Street Journal",
  "LI-0VX7YF43ID": "The Wall Street Journal",
  "LI-OGKAU33YUN": "The Wall Street Journal",
  "LI-W1OBGSNDKZ": "The Wall Street Journal",
  "LI-56DNQ0S1GQ": "The Wall Street Journal",
  "LI-TWFU9Y3TC5": "The Wall Street Journal",
  "LI-5RAPTL75FD": "The Wall Street Journal",
  "LI-0LX7XQX9F3": "The Wall Street Journal",
  "LI-SAYWWEQQIX": "The Wall Street Journal",
  "LI-2RFYBU8OPM": "The Wall Street Journal",
  "LI-9LWXZZOKE8": "The Wall Street Journal",
  "LI-OTLOPCW3GR": "NY Daily News",
  "LI-QB2H3UTBJ6": "NY Daily News",
  "LI-ALTI74K7EG": "Details",
  "LI-VTNR5WU578": "Wired",
  "LI-GXZB3DSUTE": "Conde Nast Traveler",
  "LI-AW0OGZ3BCP": "Mode Media",
  "LI-QTYRUCGD8P": "Mode Media",
  "LI-9NFMAUQZ4E": "Mode Media",
  "LI-3W60M08GIN": "Mode Media",
  "LI-XM4HKEBCNZ": "Mode Media",
  "LI-82IVMU2ZL3": "Mode Media",
  "LI-WJUBQ2OUAR": "Mode Media",
  "LI-XPA7PUW0BO": "Mode Media",
  "LI-0YKKBF0ICC": "Mode Media",
  "LI-7G3LCTKB87": "Mode Media",
  "LI-UONBADY0QZ": "Mode Media",
  "LI-E896A469IS": "Mode Media",
  "LI-14XG69FO6Q": "Mode Media",
  "LI-X00HWUPYPJ": "Mode Media",
  "LI-7YZXKMB0MG": "Mode Media",
  "LI-B5XNWPH8F8": "Mode Media",
  "LI-O8Y66U7MLL": "Mode Media",
  "LI-UCHMTMPYRR": "Mode Media",
  "LI-L14G8630IN": "Mode Media",
  "LI-2WVBFBT7SL": "Mode Media",
  "LI-1168WIWFZN": "Mode Media",
  "LI-80VW61IB53": "NY Daily News",
  "LI-432YM7ZE5L": "NY Daily News",
  "LI-IHTIRQS64H": "Bloomberg",
  "LI-TYUGLQNU8G": "Bloomberg",
  "LI-GRZLWI9JQ2": "Bloomberg",
  "LI-PCDP6T4XB3": "The Verge",
  "LI-JZUGXP3K1D": "The Verge",
  "LI-KI5SIDJ8WV": "The Verge",
  "LI-4B5R8OOKL3": "Esquire",
  "LI-17B2LUR91N": "Esquire",
  "LI-JVSUK7DV6J": "Esquire",
  "LI-DJ0QCIBPWV": "Esquire",
  "LI-W042DQKDWX": "The Wall Street Journal Digital Network",
  "LI-DK9E9B6SSX": "The Wall Street Journal Digital Network",
  "LI-X1GCFFD21R": "Mashable",
  "LI-0JA8D1Z5WK": "Mashable",
  "LI-V9PRAT6IVP": "Mashable",
  "LI-A196RWFE7K": "Mashable",
  "LI-CK15Z98TWP": "Mashable",
  "LI-7EQHBKD3MT": "Martini Inc.",
  "LI-NR15FE95M0": "Wired",
  "LI-AYZQIGCQEY": "Ars Technica",
  "LI-OYN2KO2BLA": "Wired",
  "LI-9J2RBF0J0T": "Wired",
  "LI-YSQSWJWABM": "Wired",
  "LI-B6V2Z7LIAK": "Mashable",
  "LI-TDX548DCCD": "Mashable",
  "LI-1HNSSPI9QN": "Mashable",
  "LI-68AJ37A1W2": "Gizmodo",
  "LI-S72FX0ZSXM": "Conde Nast Collections",
  "LI-WWRNEDQJWS": "Conde Nast Collections",
  "LI-GMG53P9J0X": "Mode Media",
  "LI-BPKNO2T7OF": "Mode Media",
  "LI-FVIQ6PNXBL": "Mode Media",
  "LI-YV67ZH4TX3": "Mode Media",
  "LI-SV4WPD02B5": "Mode Media",
  "LI-01FFVMA6EH": "Mode Media",
  "LI-0870H76MC8": "Mode Media",
  "LI-V7Y291YP35": "Mode Media",
  "LI-HSGEW5KIXO": "Mode Media",
  "LI-IZQ94F13D4": "Mode Media",
  "LI-6ZZRUXYFD1": "Mode Media",
  "LI-59M1KC5B8Y": "Mode Media",
  "LI-WRDHKWBKGF": "Mode Media",
  "LI-CCST3GF2Y1": "Mode Media",
  "LI-2953W60UMG": "Mode Media",
  "LI-JS157S4YX7": "Mode Media",
  "LI-UG0VLW9F1T": "Mode Media",
  "LI-NYX4CIF0YU": "Mode Media",
  "LI-NS02TIL680": "Bloomberg",
  "LI-XIYMSPDFJG": "Bloomberg",
  "LI-KU6NUNZSOE": "Conde Nast Traveler",
  "LI-AH2A1LKK0C": "Conde Nast Traveler",
  "LI-3EX1SEVMG8": "AccuWeather",
  "LI-K53JRZ04CK": "AccuWeather",
  "LI-P13DVJZ8KH": "NY Daily News",
  "LI-WW7Z6ON8X5": "Conde Nast Collections",
  "LI-S2TXXXNU7R": "Allure",
  "LI-LY6A0AF28O": "Allure",
  "LI-TIUG9A6U1L": "Allure",
  "LI-V9S8KNLCQC": "Allure",
  "LI-TVJDF6GHLP": "Allure",
  "LI-ZA5KB1ZULD": "Allure",
  "LI-ICVZAX36W1": "BBC",
  "LI-KDZK1EZ3EF": "Bloomberg",
  "LI-UXFA1F6K2W": "Bloomberg",
  "LI-VOJK6U1AD5": "Conde Nast Traveler",
  "LI-77D26L5V7G": "Conde Nast Traveler",
  "LI-EH9YFC7XM8": "Gizmodo",
  "LI-DSL2TRF2JH": "Gizmodo",
  "LI-NMVJ7C0YQ3": "Gizmodo",
  "LI-VFO9MTGTI3": "Gizmodo",
  "LI-45JYACR3H7": "Gizmodo",
  "LI-7Y4DAFH86L": "Gizmodo",
  "LI-UWEXNSWUCZ": "Gizmodo",
  "LI-7DBQYFQ8QB": "Gizmodo",
  "LI-U73RDPO7LI": "Gizmodo",
  "LI-UWE2MPYEZM": "Gizmodo",
  "LI-07UK54CJ9T": "Gizmodo",
  "LI-JCPITMPWPZ": "Gizmodo",
  "LI-3DBJNJBMPU": "Style.com",
  "LI-L759HS8TWY": "The New Yorker",
  "LI-KEZKQ67G4Z": "The New Yorker",
  "LI-JRUTQV6WMM": "The New Yorker",
  "LI-TWEY31SMPQ": "Gizmodo",
  "LI-7EHQZMJE35": "Gizmodo",
  "LI-B2QOPEKR42": "Gizmodo",
  "LI-Z2AOCSD7HT": "Gizmodo",
  "LI-L0T5LY10Q6": "Gizmodo",
  "LI-226RUO42OS": "Gizmodo",
  "LI-B3SAXTAB3E": "Gizmodo",
  "LI-2W3644CTIZ": "Gizmodo",
  "LI-PV96I2E6GI": "Gizmodo",
  "LI-XVBHP73WSU": "Gizmodo",
  "LI-KFPRH4Z4T2": "Gizmodo",
  "LI-RXNY7I4LR1": "Gizmodo",
  "LI-6ITW8TUFH6": "Glamour",
  "LI-8JA7UORKNW": "Glamour",
  "LI-3KNUJKA8XG": "StyleBlazer",
  "LI-I4DEWPQP4Y": "StyleBlazer",
  "LI-4X2SZFF86T": "StyleBlazer",
  "LI-7ZFKQUKW8I": "StyleBlazer",
  "LI-RNNFKH6LPA": "Glamour",
  "LI-XE6IT0U5L7": "GQ",
  "LI-CMG4DIHPZI": "Conde Nast Traveler",
  "LI-IQAFVTN20H": "Conde Nast Traveler",
  "LI-VRUCJEDET5": "Conde Nast Traveler",
  "LI-CIU37J607W": "Conde Nast Traveler",
  "LI-W0SVMSFEGE": "Conde Nast Traveler",
  "LI-SXYF7LEIE4": "Conde Nast Traveler",
  "LI-W2T6Z9KZLO": "CBS Interactive ",
  "LI-FVRADRTS1S": "CBS Interactive ",
  "LI-KUC3S3PQDI": "CBS Interactive ",
  "LI-D1L78WAA5I": "CBS Interactive ",
  "LI-5DT7L7ZVGQ": "CBS Interactive ",
  "LI-LDJM1GFMEF": "CBS Interactive ",
  "LI-7TV1DIVZU2": "CBS Interactive ",
  "LI-U91VWUV6XR": "CBS Interactive ",
  "LI-ATC4Y95JLP": "CBS Interactive ",
  "LI-9H1DSOV2XG": "CBS Interactive ",
  "LI-T2ZR9HQE9K": "CBS Interactive ",
  "LI-UVN2SGOD7O": "CBS Interactive ",
  "LI-ZQPWLWNJN3": "CBS Interactive ",
  "LI-W0R0QKH1DA": "CBS Interactive ",
  "LI-B8RH3681D2": "CBS Interactive ",
  "LI-C9N4QF7FX1": "CBS Interactive ",
  "LI-8Y57HPFQ01": "CBS Interactive ",
  "LI-LSKQMBCL91": "CBS Interactive ",
  "LI-0QA7HJPX3X": "CBS Interactive ",
  "LI-CGYQ22U8F9": "CBS Interactive ",
  "LI-3SVUQPBG18": "Trulia",
  "LI-H3K9Q4PE9Y": "Trulia",
  "LI-CZAW2MFY4W": "Trulia",
  "LI-07MLZY05EZ": "Trulia",
  "LI-F0CH2V8Q8M": "RantSports",
  "LI-BVOUXR3JBI": "RantSports",
  "LI-WT1Z8T6FQK": "RantSports",
  "LI-2OZOEVUXOM": "Mode Media",
  "LI-6I1N54RMUS": "Mode Media",
  "LI-O2BINB6PAY": "Hearst Magazines Sites",
  "LI-0Q0ZVC9HAB": "Harper's Bazaar",
  "LI-Y37S7410O4": "Hearst Magazines Sites",
  "LI-O7U4ZYP91P": "Hearst Magazines Sites",
  "LI-7KMPR224OE": "Hearst Magazines Sites",
  "LI-1XIISF9TGM": "Hearst Magazines Sites",
  "LI-FFZQRN0O9E": "Harper's Bazaar",
  "LI-Q7RGDVO50T": "ELLE",
  "LI-CJ89EWMAG0": "ELLE",
  "LI-H9AD3ZYK0V": "ELLE",
  "LI-9PY7I5YUNR": "Harper's Bazaar",
  "LI-EBTF8EUTZ4": "ELLE",
  "LI-G0YAVF0BOE": "ELLE",
  "LI-8TERI0S7MK": "USA TODAY",
  "LI-V8QJJJOYXL": "USA TODAY",
  "LI-TZYD2Z2BF9": "USA TODAY",
  "LI-LGUZCB4BKB": "USA TODAY",
  "LI-1OYXMONQ6F": "USA TODAY",
  "LI-LOK6ICOJJI": "USA TODAY",
  "LI-OSHHKYES10": "USA TODAY",
  "LI-FSYEGD41M9": "Gannett",
  "LI-C75UHDH81R": "Gannett",
  "LI-O99VIZLA62": "Gannett",
  "LI-BNN491HZ0O": "Gannett",
  "LI-Z4429PO5FR": "Gannett",
  "LI-OXSJPE6VEI": "USA TODAY",
  "LI-8ZWI3FQ8P3": "USA TODAY",
  "LI-G60LBA2DQC": "USA TODAY",
  "LI-HSDAQ7J0XK": "USA TODAY",
  "LI-ZKS8E2L4Y2": "USA TODAY",
  "LI-WUE799N3KE": "USA TODAY",
  "LI-L7308FBODS": "USA TODAY",
  "LI-0FE6L9YYU8": "USA TODAY",
  "LI-UORLH8T56A": "USA TODAY",
  "LI-C3HL2U67EL": "USA TODAY",
  "LI-QI1INDL8UW": "USA TODAY",
  "LI-JC9C2B9JEX": "USA TODAY",
  "LI-DFM9IGACK4": "USA TODAY",
  "LI-VOFEJQDOUI": "USA TODAY",
  "LI-GMG5RN4JEJ": "GQ",
  "LI-6FTKUK1WJG": "GQ",
  "LI-K7RIX5JJCO": "Vanity Fair",
  "LI-P9HZQC9EDR": "GQ",
  "LI-L2PKUFSVLX": "GQ",
  "LI-43NR02FMZ1": "GQ",
  "LI-W4JYULVPVD": "GQ",
  "LI-K3AO6VKBR3": "GQ",
  "LI-ZJ9SXHWW8O": "GQ",
  "LI-Z2NK0M7VMP": "GQ",
  "LI-0N1HH5CARU": "GQ",
  "LI-WAM62O2X5W": "GQ",
  "LI-YKKZK6MSCN": "GQ",
  "LI-SL0PGGVN0G": "Vogue",
  "LI-1C7TNM0BC6": "Vogue",
  "LI-4P5IF5DFVW": "Vogue",
  "LI-F5LSHEHE1S": "Vogue",
  "LI-GHW6G2WBSQ": "Vogue",
  "LI-FN3MA0G832": "Vogue",
  "LI-PL60GDOWIB": "Vogue",
  "LI-9LFBH3ELYB": "Vogue",
  "LI-N7PEBUN24W": "Vogue",
  "LI-SQ21IOFHRW": "Vogue",
  "LI-GNP0CRCMD8": "Vogue",
  "LI-5NJAY7TXAG": "Vogue",
  "LI-SWO9FCAF7Z": "Vogue",
  "LI-X4D1CPP9XC": "Vogue",
  "LI-D43PLCZN3P": "Vogue",
  "LI-LA4W0UEEID": "Vogue",
  "LI-L0VZ5OR49K": "Vogue",
  "LI-GEMQKNT1R4": "Vogue",
  "LI-5M2ZE9VQLU": "Vogue",
  "LI-L2EVYVG50I": "Vogue",
  "LI-HP1ZNV20D7": "Vogue",
  "LI-L9WXZ2SOSP": "Vogue",
  "LI-TL97MQAURW": "Vogue",
  "LI-YUKS7O5T4C": "Vogue",
  "LI-LB7JZBINF2": "Vogue",
  "LI-DV53Q4TURQ": "Vogue",
  "LI-T0DXCGE6ZR": "Vogue",
  "LI-4JV5FOS80L": "Vogue",
  "LI-J19F350348": "Vogue",
  "LI-BB78FGD81T": "Vogue",
  "LI-B1YGEHY0HO": "Vogue",
  "LI-23WGIT51Y7": "Vogue",
  "LI-E3UBIKDQ0D": "Vogue",
  "LI-5DLC4C0FXR": "Vogue",
  "LI-IX9PBCXGJH": "Vogue",
  "LI-Z2NBFFCJOL": "IDG Tech Network CSMB Sites",
  "LI-RRV0L1GDB4": "IDG Tech Network CSMB Sites",
  "LI-KD48CRJJV0": "IDG Tech Network CSMB Sites",
  "LI-3QVGJWMU9P": "IDG Tech Network CSMB Sites",
  "LI-8I9ATXELBB": "Trulia",
  "LI-96VTU896PM": "Trulia",
  "LI-9C0012LR56": "Zillow.com",
  "LI-FJ3R6AH74I": "Zillow.com",
  "LI-DVS5TYVJ1U": "USA TODAY",
  "LI-7DOO82QHD1": "Gannett",
  "LI-TERZZ051JJ": "Gannett",
  "LI-Z5EXB4OF6J": "Mode Media",
  "LI-B3JONXZOW7": "Mode Media",
  "LI-RSWAW15N5D": "Walmart"
}

module.exports = propNames
